name: Continuous Integration for Running Test with Jest

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          
      - name: Install dependencies
        run: npm install

      - name: Run test suites
        run: npm run test-with-coverage
